name: Test and Build OpenSearch Simple Schema Backend Plugin

on:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/**'

jobs:
  build:
    strategy:
      matrix:
        java:
          - 11
          - 17

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      # dependencies: OpenSearch-sql
#      - name: Checkout Opensearch-SQL-Plugin
#        uses: actions/checkout@v2
#        with:
#          repository: 'opensearch-project/sql'
#          path: OpenSearch-SQL
#          ref: ${{ env.OPENSEARCH_VERSION }}
#      - name: Build Opensearch-SQL-Plugin
#        working-directory: ./OpenSearch-SQL
#        run: ./gradlew publishToMavenLocal -Dbuild.snapshot=false

#      - name: Run Backwards Compatibility Tests
#        run: |
#          cd services
#          echo "Running backwards compatibility tests ..."
#          ./gradlew bwcTestSuite -Dtests.security.manager=false

      - name: Build with Gradle
        run: |
          ./gradlew build

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          flags: opensearch-simpleschema
          directory: opensearch-simpleschema/
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Create Artifact Path
        run: |
          mkdir -p simpleschema-builds
          cp -r ./build/distributions/*.jar simpleschema-builds/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: opensearch-simpleschema
          path: simpleschema-builds
